/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

export function Blaze(props) {
  const { nodes, materials } = useGLTF('/Blaze.glb')
  const group = useRef();

  // useGSAP(() => {
  //   gsap.from(group.current.rotation, {
  //     y: Math.PI / 2,
  //     duration: 1,
  //     ease: 'power3.out',
  //   });
  // });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_5761e85a-8fbd-42a3-a495-afbf54115440'].geometry}
        material={materials['tripo_mat_5761e85a-8fbd-42a3-a495-afbf54115440']}
        scale={[1.47, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/Blaze.glb')
