/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Algirdas Lalys (https://sketchfab.com/alalys)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-928c4eb3c875463bbde6fda85b7d8b3a
Title: Tv
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations, useVideoTexture } from '@react-three/drei';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

export function SmartTV(props) {
  const { nodes, materials } = useGLTF('models/smarttv.glb')
  const group = useRef();
//   const { actions } = useAnimations(animations, group);

  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4');

  useEffect(() => {
    if (txt) {
    txt.rotate = Math.PI/2;
      txt.flipY = false;
    }
  }, [txt]);

  return (
    <group {...props} dispose={null}>
      <group scale={0.225}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tv1_0.geometry}
          material={materials.Tv1_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tv1_1.geometry}
          material={materials.Tv1_Glass_Material}
        >
             <meshBasicMaterial map={txt} />
            </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tv1_2.geometry}
          material={materials.Tv1_Stand_Material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/smarttv.glb')
