/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Algirdas Lalys (https://sketchfab.com/alalys)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tv-928c4eb3c875463bbde6fda85b7d8b3a
Title: Tv
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations, useVideoTexture } from '@react-three/drei';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

export function SmartTV(props) {
  const { nodes, materials,animations } = useGLTF('models/stv4.glb')
  const group = useRef();
  const { actions } = useAnimations(animations, group);

  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4');

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.225}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tv1_0.geometry}
          material={materials.Tv1_Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tv1_1.geometry}
          material={materials.Tv1_Glass_Material}
          // rotation={[0,0,Math.PI/2]}
        >
             <meshBasicMaterial map={txt} />
            </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tv1_2.geometry}
          material={materials.Tv1_Stand_Material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/stv4.glb')
